USE [master]
GO
/****** Object:  Database [SimuladorPinturas]    Script Date: 25/04/2025 11:25:36 a. m. ******/
CREATE DATABASE [SimuladorPinturas]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SimuladorPinturas', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SimuladorPinturas.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SimuladorPinturas_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SimuladorPinturas_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [SimuladorPinturas] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SimuladorPinturas].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SimuladorPinturas] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SimuladorPinturas] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SimuladorPinturas] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SimuladorPinturas] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SimuladorPinturas] SET ARITHABORT OFF 
GO
ALTER DATABASE [SimuladorPinturas] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [SimuladorPinturas] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SimuladorPinturas] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SimuladorPinturas] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SimuladorPinturas] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SimuladorPinturas] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SimuladorPinturas] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SimuladorPinturas] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SimuladorPinturas] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SimuladorPinturas] SET  ENABLE_BROKER 
GO
ALTER DATABASE [SimuladorPinturas] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SimuladorPinturas] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SimuladorPinturas] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SimuladorPinturas] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SimuladorPinturas] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SimuladorPinturas] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SimuladorPinturas] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SimuladorPinturas] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SimuladorPinturas] SET  MULTI_USER 
GO
ALTER DATABASE [SimuladorPinturas] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SimuladorPinturas] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SimuladorPinturas] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SimuladorPinturas] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SimuladorPinturas] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SimuladorPinturas] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [SimuladorPinturas] SET QUERY_STORE = ON
GO
ALTER DATABASE [SimuladorPinturas] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [SimuladorPinturas]
GO
/****** Object:  Table [dbo].[Historial_Simulaciones]    Script Date: 25/04/2025 11:25:36 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Historial_Simulaciones](
	[ID_Historial] [int] IDENTITY(1,1) NOT NULL,
	[ID_Usuario] [int] NOT NULL,
	[Configuracion_Color] [nvarchar](max) NULL,
	[Fecha_Simulacion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Historial] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuarios]    Script Date: 25/04/2025 11:25:37 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[ID_Usuario] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
	[Correo_Electronico] [nvarchar](100) NOT NULL,
	[Contrasena] [nvarchar](255) NOT NULL,
	[Fecha_Registro] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__Usuarios__859478167432E117]    Script Date: 25/04/2025 11:25:37 a. m. ******/
ALTER TABLE [dbo].[Usuarios] ADD UNIQUE NONCLUSTERED 
(
	[Correo_Electronico] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Historial_Simulaciones] ADD  DEFAULT (getdate()) FOR [Fecha_Simulacion]
GO
ALTER TABLE [dbo].[Usuarios] ADD  DEFAULT (getdate()) FOR [Fecha_Registro]
GO
ALTER TABLE [dbo].[Historial_Simulaciones]  WITH CHECK ADD FOREIGN KEY([ID_Usuario])
REFERENCES [dbo].[Usuarios] ([ID_Usuario])
GO
USE [master]
GO
ALTER DATABASE [SimuladorPinturas] SET  READ_WRITE 
GO
